"""Disclosure and compliance artefacts.

This module exists because of a specific legal fact: an AI-generated video that
looks like drone footage, when the source was only still photography, is a
disclosure problem even when every source photo is genuine. The images are real.
The flight is not.

Verified requirements this implements (checked 2026-08-20):

  NAR Code of Ethics, Article 12 and Standard of Practice 12-5
      REALTORS(R) must present a true picture and must disclose the status of any
      altered photograph. Binds every REALTOR(R) nationally, in every state.

  California AB 723 -> Business & Professions Code sec. 10140.8
      Approved 2025-10-10, effective 2026-01-01. A broker, salesperson, OR A
      PERSON ACTING ON THEIR BEHALF who puts a digitally altered image in an
      advertisement must include a conspicuous statement that the image was
      modified AND provide a link to the original unaltered image via website,
      URL, or QR code. Where the ad is on a website, the unaltered image itself
      must be included. Routine edits -- lighting, sharpening, white balance,
      colour correction, angle, straightening, cropping, exposure -- are
      excluded, because they do not change the representation of the property.

  MLS enforcement
      Non-disclosure of virtual staging commonly draws fines in the
      $500-$5,000 range depending on the board.

"A person acting on their behalf" is the clause that matters commercially: the
vendor producing the video is inside the statute, not outside it. So disclosure
is generated by the pipeline for every job and cannot be forgotten by an agent.

This is not legal advice. Rules vary by MLS and by state and they move. Have a
real estate attorney in each operating state review the disclosure text before
it goes out, and re-check board rules quarterly.
"""

from __future__ import annotations

import html
import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import segno

FFMPEG = shutil.which("ffmpeg") or "ffmpeg"
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# The on-screen line. Deliberately plain: "conspicuous" is the statutory test, and
# a hedged or decorative phrasing fails it.
CARD_HEADLINE = "AI-GENERATED VIDEO"
CARD_BODY = (
    "Camera motion in this video is AI-generated from still photographs "
    "of this property. It is not drone or walkthrough footage."
)
CARD_CTA = "Original unaltered photos:"

# Text for the MLS remarks / listing caption field.
CAPTION = (
    "AI-generated video. The camera movement was created from still photographs "
    "of this property using AI; this is not drone or walkthrough footage. "
    "The original, unaltered photographs are available at {url}"
)

# Short form for social captions where characters are tight.
CAPTION_SHORT = (
    "AI-generated motion from real listing photos -- not drone footage. "
    "Originals: {url}"
)


@dataclass
class DisclosurePack:
    """Everything one job needs to be disclosed correctly."""

    card: Path              # burned-in opening card
    page: Path              # hosted page carrying the unaltered originals
    qr: Path
    caption: str
    caption_short: str
    url: str


def make_qr(url: str, out: str | Path, *, scale: int = 8) -> Path:
    """QR to the originals page. AB 723 names a QR code as an accepted link."""
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    segno.make(url, error="h").save(str(out), scale=scale, border=2)
    return out


def _esc(text: str) -> str:
    """Escape for ffmpeg drawtext, which treats : ' \\ and % specially."""
    return (
        text.replace("\\", "\\\\")
        .replace(":", "\\:")
        .replace("'", "\\'")
        .replace("%", "\\%")
    )


def _wrap(text: str, width: int) -> list[str]:
    words, lines, cur = text.split(), [], ""
    for w in words:
        trial = f"{cur} {w}".strip()
        if len(trial) <= width:
            cur = trial
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def make_card(
    url: str,
    out: str | Path,
    *,
    seconds: float = 2.5,
    width: int = 1920,
    height: int = 1080,
    fps: int = 24,
) -> Path:
    """Render the opening disclosure card as a video clip.

    Burned into the head of the master rather than left to a caption, because a
    caption does not travel: the file gets re-posted to Instagram, emailed, and
    embedded, and the disclosure has to survive all three.
    """
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)

    body = _wrap(CARD_BODY, 58)
    draws = [
        f"drawtext=fontfile={FONT_BOLD}:text='{_esc(CARD_HEADLINE)}':"
        f"fontcolor=white:fontsize=64:x=(w-tw)/2:y=h*0.30",
    ]
    for i, line in enumerate(body):
        draws.append(
            f"drawtext=fontfile={FONT}:text='{_esc(line)}':"
            f"fontcolor=0xDDDDDD:fontsize=38:x=(w-tw)/2:y=h*0.44+{i * 52}"
        )
    draws.append(
        f"drawtext=fontfile={FONT}:text='{_esc(CARD_CTA + ' ' + url)}':"
        f"fontcolor=0x9AD5FF:fontsize=30:x=(w-tw)/2:y=h*0.72"
    )

    subprocess.run(
        [FFMPEG, "-y", "-loglevel", "error",
         "-f", "lavfi", "-i", f"color=c=0x101418:s={width}x{height}:d={seconds}:r={fps}",
         "-vf", ",".join(draws),
         "-c:v", "libx264", "-crf", "18", "-preset", "medium",
         "-pix_fmt", "yuv420p", str(out)],
        check=True, capture_output=True, text=True,
    )
    return out


PAGE_CSS = """
:root{--bg:#ffffff;--fg:#14181d;--muted:#5b6673;--line:#e4e8ee;--accent:#0b5cd6;--card:#f7f9fc}
:root:not([data-theme=light]){}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#0e1116;--fg:#e8ecf1;--muted:#9aa5b3;--line:#232a33;--accent:#6fb0ff;--card:#161b22}}
:root[data-theme=dark]{--bg:#0e1116;--fg:#e8ecf1;--muted:#9aa5b3;--line:#232a33;--accent:#6fb0ff;--card:#161b22}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:1000px;margin:0 auto;padding:40px 20px 80px}
h1{font-size:1.6rem;margin:0 0 4px}
.addr{color:var(--muted);margin:0 0 28px}
.notice{background:var(--card);border:1px solid var(--line);border-left:4px solid var(--accent);border-radius:8px;padding:18px 20px;margin:0 0 32px}
.notice h2{font-size:1rem;margin:0 0 8px;text-transform:uppercase;letter-spacing:.06em}
.notice p{margin:0 0 8px;color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px}
figure{margin:0;background:var(--card);border:1px solid var(--line);border-radius:8px;overflow:hidden}
figure img{display:block;width:100%;height:auto}
figcaption{padding:10px 12px;font-size:.85rem;color:var(--muted);text-transform:capitalize}
footer{margin-top:44px;padding-top:20px;border-top:1px solid var(--line);color:var(--muted);font-size:.85rem}
"""


def make_page(
    listing: str,
    photos: list[dict],
    out: str | Path,
    *,
    url: str,
    produced_by: str = "FlyThrough",
) -> Path:
    """Build the hosted originals page.

    This is the artefact AB 723 asks for: the unaltered images, reachable from
    the advertisement by URL or QR. Photos are referenced by filename, so the
    page ships next to a folder of the agent's own originals -- it never embeds a
    re-encoded copy, because a re-encode is itself an alteration.
    """
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)

    cards = "\n".join(
        f'      <figure><img src="originals/{html.escape(Path(p["path"]).name)}" '
        f'alt="{html.escape(p["room_key"].replace("_", " "))}" loading="lazy">'
        f'<figcaption>{html.escape(p["room_key"].replace("_", " "))}</figcaption></figure>'
        for p in photos
    )

    doc = f"""<title>Original Photos — {html.escape(listing)}</title>
<style>{PAGE_CSS}</style>
<div class="wrap">
  <h1>Original, unaltered photographs</h1>
  <p class="addr">{html.escape(listing)}</p>

  <div class="notice">
    <h2>About the video</h2>
    <p>The listing video for this property is an <strong>AI-generated video</strong>.
       The camera movement was created from the still photographs on this page.
       It is not drone footage and it is not a walkthrough recording.</p>
    <p>Every photograph below is the original file supplied by the listing agent,
       unaltered. Nothing on this page has been staged, retouched or generated.</p>
  </div>

  <div class="grid">
{cards}
  </div>

  <footer>
    Published to satisfy disclosure of digitally altered imagery, including
    California Business &amp; Professions Code &sect;10140.8 and NAR Code of Ethics
    Article 12. Page URL: {html.escape(url)} &middot; Produced by {html.escape(produced_by)}.
  </footer>
</div>
"""
    out.write_text(doc)
    return out


def build_pack(
    listing: str,
    photos: list[dict],
    outdir: str | Path,
    *,
    url: str,
    slug: str,
) -> DisclosurePack:
    """Produce every disclosure artefact for one job."""
    outdir = Path(outdir)
    card = make_card(url, outdir / f"{slug}_disclosure_card.mp4")
    qr = make_qr(url, outdir / f"{slug}_originals_qr.png")
    page = make_page(listing, photos, outdir / "originals.html", url=url)

    pack = DisclosurePack(
        card=card, page=page, qr=qr, url=url,
        caption=CAPTION.format(url=url),
        caption_short=CAPTION_SHORT.format(url=url),
    )
    (outdir / f"{slug}_disclosure.json").write_text(json.dumps({
        "listing": listing,
        "url": url,
        "caption_mls": pack.caption,
        "caption_social": pack.caption_short,
        "card": str(card),
        "qr": str(qr),
        "page": str(page),
        "basis": [
            "NAR Code of Ethics Article 12 / Standard of Practice 12-5",
            "California Business & Professions Code 10140.8 (AB 723), effective 2026-01-01",
        ],
        "not_legal_advice": True,
    }, indent=2))
    return pack
