#!/usr/bin/env python3
"""Export the priced offer set to site/pricing.json.

    python3 model/export_pricing.py

The website must never carry a price that was typed into HTML. Property tiers
live in model/unit_economics.py, vehicle products in model/ad_pricing.py, and
both are margin-checked against the verified render rate. This script is the
only bridge between them and the page: change a price in the model, rebuild,
and the site follows. Nothing else is allowed to know a number.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "model"))
sys.path.insert(0, str(ROOT / "pipeline"))

from ad_pricing import BANDS, LOT_PLANS, PRODUCTS            # noqa: E402
from catalog import CATALOG, INTAKE                          # noqa: E402
from unit_economics import RETAINER_LISTINGS, RETAINER_PRICE, TIERS  # noqa: E402

OUT = ROOT / "site" / "pricing.json"

# Customer-facing bullets. The MODEL owns the number; this owns the sentence.
# Keyed by product name so a rename in the model surfaces here as a KeyError
# rather than as a silently unlabelled card on a live page.
PROPERTY_COPY = {
    "Single Listing": ("one property · 30 seconds", [
        "16:9 master + thumbnail",
        "Full disclosure pack",
        "24-hour delivery",
        "One revision",
    ]),
    "Listing Pro": ("one property · 42 seconds", [
        "Everything in Single",
        "9:16 vertical for Reels",
        "MLS + social caption text",
        "Two revisions",
    ]),
    "Signature": ("luxury listing · 60 seconds", [
        "Everything in Pro",
        "Twilight pass on the exterior",
        "Priority turnaround",
        "Three revisions",
    ]),
}

VEHICLE_COPY = {
    "Walkaround x3": ("three vehicles · 20 seconds each", [
        "$39 a vehicle — three-vehicle minimum",
        "9:16 + 16:9 + thumbnail",
        "Folder drop, 24h turnaround",
        "You own them outright",
    ]),
    "Walkaround (per VIN)": ("per vehicle · 20 seconds", [
        "Every VIN, not just the halo cars",
        "9:16 + 16:9 + thumbnail",
        "Folder drop, 24h turnaround",
        "You own it outright",
    ]),
    "Ad cut - mainstream": ("per vehicle · 15 seconds", [
        "Briefed to the unit, not a template",
        "Detail beats: wheels, seats, screen, bed",
        "Vertical-first cut for paid social",
        "Under $80k inventory",
    ]),
    "Ad cut - premium": ("per vehicle · 16 seconds", [
        "Hype tempo, showroom lighting",
        "Opens on the badge, closes on the stance",
        "Every option the buyer is paying for",
        "Exotic, luxury and performance",
    ]),
    "Launch package": ("new arrival · 16 seconds", [
        "Everything in Premium",
        "Three platform re-cuts",
        "Three hook variants for paid social",
        "First-week push on a new arrival",
    ]),
}

FEATURED = {"Listing Pro", "Ad cut - premium"}


def sku_for(name: str) -> str:
    """Link a displayed card to the SKU that takes the money. Exact-name match,
    and it raises rather than silently rendering a card nobody can buy."""
    hits = [c.id for c in CATALOG if c.name == name]
    if len(hits) != 1:
        raise KeyError(f"{name!r} matches {len(hits)} SKUs; the catalogue and "
                       f"the price models have drifted apart")
    return hits[0]


def build() -> dict:
    prop = []
    for t in TIERS:
        per, bullets = PROPERTY_COPY[t.name]
        prop.append({"sku": sku_for(t.name), "name": t.name, "price": t.price, "per": per,
                     "bullets": bullets, "featured": t.name in FEATURED,
                     "note": t.note})

    veh = []
    for p in PRODUCTS:
        if p.channel != "online":
            continue          # a rate, not a card -- there is nothing to buy
        per, bullets = VEHICLE_COPY[p.name]
        m = p.margin()
        veh.append({"sku": sku_for(p.name), "name": p.name, "price": p.price, "per": per,
                    "bullets": bullets, "featured": p.name in FEATURED,
                    "note": p.note, "seconds": p.seconds, "beats": p.beats,
                    "render_usd": round(m["render"], 2)})

    bands = [{"band": b, "product": prod, "price": price, "why": why}
             for b, prod, price, why in BANDS]

    return {
        "_note": "GENERATED by model/export_pricing.py -- do not edit. "
                 "Prices come from model/unit_economics.py and model/ad_pricing.py.",
        "property": prop,
        "vehicle": veh,
        "bands": bands,
        "retainer": {"sku": "re-retainer",
                     "price": RETAINER_PRICE, "listings": RETAINER_LISTINGS,
                     "per_listing": round(RETAINER_PRICE / RETAINER_LISTINGS, 2)},
        "lot_plans": [{"sku": f"lot-{lp.units}", "name": lp.name,
                       "units": lp.units, "price": lp.price,
                       "per_unit": round(lp.per_unit, 2)} for lp in LOT_PLANS],
        "catalog": [{"id": s.id, "name": s.name, "price": s.price,
                     "mode": s.mode, "vertical": s.vertical,
                     "turnaround": s.turnaround, "quantity": s.quantity,
                     "unit_price": round(s.unit_price, 2),
                     "blurb": s.blurb, "tags": list(s.tags)} for s in CATALOG],
        "intake": INTAKE,
    }


if __name__ == "__main__":
    data = build()
    OUT.write_text(json.dumps(data, indent=2) + "\n")
    print(f"  wrote {OUT}")
    print(f"    {len(data['property'])} property tiers, "
          f"{len(data['vehicle'])} vehicle products, {len(data['bands'])} bands, "
          f"{len(data['lot_plans'])} lot plans, "
          f"{len(data['catalog'])} sellable SKUs")
