#!/usr/bin/env python3
"""Generate the vehicle and product shot guides from their own taxonomies.

    python3 docs/shot_guide_ads.py

Writes into docs/:
    shot-guide-vehicle.md    for a dealer's lot photographer
    shot-guide-product.md    for a brand sending product stills

Same reason docs/shot_guide.py is generated rather than written: the rules live
in vehicles.TOUR_ORDER / REQUIRED_ANCHORS / NON_HERO and products.*, and a
hand-written guide drifts from the validator the first time either changes. The
drift surfaces as a customer who followed the instructions and still got a
warning, which is the worst possible place to discover it.

Deliberately NOT merged with the property guide. Its copy is built around a
buyer walking a house and an aerial rule that has no analogue here; a dealer
needs to hear about proof shots and trim options instead. A shared template
would produce two worse guides, so what is shared is the taxonomy, not the prose.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "pipeline"))

from flythrough import products, vehicles      # noqa: E402

OUT = ROOT / "docs"

HEADER = """<!-- GENERATED by docs/shot_guide_ads.py -- do not edit by hand.
     Rules come from vehicles/products TOUR_ORDER, REQUIRED_ANCHORS and
     NON_HERO. Change those, then re-run the generator. -->
"""

VEHICLE_PLAIN = {
    "hero": "Three-quarter front — the beauty shot",
    "front": "Straight on the nose", "driver_side": "Full driver-side profile",
    "rear": "Straight on the back", "passenger_side": "Full passenger-side profile",
    "wheels": "One wheel, filling the frame", "engine": "Engine bay, hood up",
    "door_open": "Driver's door open, from outside",
    "dash": "Dashboard and steering wheel", "front_seats": "Front seats",
    "rear_seats": "Back seats", "infotainment": "The centre screen, powered on",
    "cargo": "Trunk, bed or cargo area", "odometer": "The odometer",
    "vin": "VIN plate or window sticker", "undercarriage": "Underside",
}

VEHICLE_HOW = {
    "hero": "Front corner, camera at headlight height, wheels turned slightly toward you. This is the frame the ad opens on.",
    "front": "Square to the grille, camera level, centred between the headlights.",
    "driver_side": "Square to the middle of the car, far enough back to get bumper to bumper with no cropping.",
    "rear": "Square to the tailgate, camera level.",
    "passenger_side": "Same as the driver side, from the other face.",
    "wheels": "Crouch. One wheel filling the frame, caliper and badge visible.",
    "engine": "Hood fully up, shot from the front corner so the bay is not foreshortened.",
    "door_open": "Door wide, shot from outside looking in. This is the frame that carries the camera from outside to inside.",
    "dash": "From the driver's seat headrest, screen and gauges both in frame.",
    "front_seats": "From the open driver's door, both front seats visible.",
    "rear_seats": "From the open rear door, seat backs and legroom visible.",
    "infotainment": "Screen ON and showing the home screen. A dark screen sells nothing.",
    "cargo": "Tailgate or hatch open, shot square from behind.",
    "odometer": "Ignition on so the number is lit and legible.",
    "vin": "Close enough to read. Door jamb plate or the window sticker.",
    "undercarriage": "Only if it is clean and you are selling that.",
}

PRODUCT_PLAIN = {
    "hero": "Three-quarter beauty shot", "front": "Straight on the front",
    "side": "Straight on the side", "back": "Straight on the back",
    "top": "From directly above", "detail": "One close detail",
    "material": "The surface, close", "open": "Opened, unfolded or unzipped",
    "interior": "Inside", "scale": "Beside something of known size",
    "in_use": "Being used", "packaging": "The box or wrap",
    "accessories": "What comes with it", "colorway": "Other finishes",
    "size_chart": "Size or spec chart", "label": "Ingredients or spec panel",
}

PRODUCT_HOW = {
    "hero": "Turned slightly off square so two faces show. This is the frame the film opens on.",
    "front": "Dead square, centred, camera at the product's mid-height.",
    "side": "Dead square from one side.",
    "back": "Dead square from behind.",
    "top": "Directly overhead, product centred.",
    "detail": "Fill the frame with the stitching, weld, grain or edge you are proud of.",
    "material": "Close enough that texture reads. Rake the light across it, do not flatten it.",
    "open": "Whatever state a buyer wants to see it in — lid off, unfolded, unzipped.",
    "interior": "Inside, lit so it is not a black hole.",
    "scale": "Next to a hand, a phone, a coin — anything a buyer already knows the size of.",
    "in_use": "In the situation it is for.",
    "packaging": "The box as it arrives.",
    "accessories": "Everything in the box, laid out.",
    "colorway": "The same angle as the hero, in each finish.",
    "size_chart": "Flat, square, legible.",
    "label": "Flat, square, legible.",
}


def _table(mod, plain: dict[str, str]) -> str:
    rows = []
    for key in mod.TOUR_ORDER:
        req = "**required**" if key in mod.REQUIRED_ANCHORS else ""
        note = "never used as the cover frame" if key in mod.NON_HERO else ""
        rows.append(f"| {plain.get(key, key)} | `{key}` | {req} | {note} |")
    return "\n".join(rows)


def _anchors(mod, plain: dict[str, str], how: dict[str, str]) -> str:
    return "\n".join(
        f"{i}. **{plain[a]}** — {how[a]}"
        for i, a in enumerate(mod.REQUIRED_ANCHORS, 1))


def vehicle_guide() -> str:
    m = vehicles
    return f"""{HEADER}
# What to photograph — vehicles

You almost certainly already shoot most of this. This is about **which frames we
need and where the camera stands**, so the film moves between them cleanly.

## The short version

- **Shoot the whole walk in one lap.** Do not move the car between shots.
- **Landscape, not portrait.**
- **Originals.** No filters, no dealer overlay, no watermark burned in.
- **Name the file after the frame**: `hero.jpg`, `wheels.jpg`, `dash.jpg`.
- **One folder per VIN.** Mixed folders are the single most common cause of a
  film that cuts to a different car.

## The three we cannot cut without

{_anchors(m, VEHICLE_PLAIN, VEHICLE_HOW)}

## Everything else, in the order we use it

Order in the folder does not matter. We sequence it.

| Frame | Name the file | | |
|---|---|---|---|
{_table(m, VEHICLE_PLAIN)}

## The rule that matters most

**Do not jump from one side of the car to the opposite side with nothing in
between.** If you shoot the driver side and then the passenger side, there is no
path a real camera could travel between them without going around — so the film
has to cross the body, and the car warps on the way. Shoot the nose or the tail
as the bridge. We check this before rendering and will tell you if it is missing.

The same applies going inside: **the open-door frame is what carries the camera
from outside to inside.** Without it, the cut from exterior to dash is a jump.

## Sell the options

Whatever the buyer is paying extra for, photograph it on its own — the wheels,
the leather, the tow package, the screen, the bed liner. A walkaround that shows
a truck but never shows the red leather is not selling the red leather.

## What makes a frame unusable

- Portrait orientation
- Dealer plate frames, price stickers or watermarks burned into the image
- A dark infotainment screen
- Another vehicle overlapping the subject
- People in frame
- Wet paint from a wash that is still beading — it reads as noise and the camera
  move will crawl on it

## What happens next

Send the folder. We check it, flag anything missing within a couple of hours,
and deliver the next day.
"""


def product_guide() -> str:
    m = products
    return f"""{HEADER}
# What to photograph — products

The film is built from your stills. Every shot begins and ends on a real
photograph of the real product; the camera move between them is the only thing
generated. So the stills are the whole job.

## The short version

- **One product per folder.**
- **Same lighting and same background for every frame.** This matters more here
  than anywhere else: the camera has to travel between two of your photos, and if
  the light changes between them the move looks like a cut.
- **Originals.** No filters, no added shadows, no background swaps.
- **Name the file after the frame**: `hero.jpg`, `detail.jpg`, `scale.jpg`.

## The three we cannot cut without

{_anchors(m, PRODUCT_PLAIN, PRODUCT_HOW)}

## Everything else, in the order we use it

| Frame | Name the file | | |
|---|---|---|---|
{_table(m, PRODUCT_PLAIN)}

## Two things to know before you send

**1. Photographs with people in them.** `in_use` and `scale` frames often contain
a real person. We accept them, but tell us — generating motion across a
photograph of an identifiable person is a different legal question from moving a
camera past a handbag, and some platforms treat it differently. It is flagged at
intake either way.

**2. We make no claims.** The film shows the product. It will not say it is the
best, the fastest or the only one, and it will not carry a testimonial. The FTC
rule on consumer reviews and testimonials (in force since October 2024) bans
AI-generated testimonials outright — **regardless of disclosure** — with
penalties per violation in the tens of thousands. Product claims are yours to
make in the caption, where you can stand behind them.

## What makes a frame unusable

- Different background or lighting from the rest of the set
- A drop shadow or reflection added in post
- Heavy retouching — we do not edit your photos, so what you send is what ships
- Screenshots, or images re-saved from a message thread

## What happens next

Send the folder. We check it, flag anything missing within a couple of hours,
and deliver the next day.
"""


def _prose(text: str) -> str:
    """These files are read by clients, not developers. A double hyphen is an
    editing convention, not punctuation -- it renders literally as "--" in the
    published page, which looks like a typo to the person following the guide."""
    return text.replace(" -- ", " \u2014 ")


def main() -> int:
    files = {
        "shot-guide-vehicle.md": vehicle_guide(),
        "shot-guide-product.md": product_guide(),
    }
    for name, body in files.items():
        (OUT / name).write_text(_prose(body))
        print(f"  wrote {name}  ({len(body.splitlines())} lines)")

    # Acceptance: every key named in a guide must resolve through its own module,
    # and every taxonomy key must be named. A guide that omits a frame we plan
    # for is how a customer ends up short a shot they were never asked for.
    bad = []
    for mod, plain, how in ((vehicles, VEHICLE_PLAIN, VEHICLE_HOW),
                            (products, PRODUCT_PLAIN, PRODUCT_HOW)):
        for k in mod.TOUR_ORDER:
            if k not in plain:
                bad.append(f"{mod.__name__}: {k} has no plain name")
            if k not in how:
                bad.append(f"{mod.__name__}: {k} has no instruction")
            if mod.resolve(k).key != k:
                bad.append(f"{mod.__name__}: {k} does not resolve to itself")
    if bad:
        for b in bad:
            print(f"  FAIL: {b}")
        return 1
    print(f"  {len(vehicles.TOUR_ORDER)} vehicle frames and "
          f"{len(products.TOUR_ORDER)} product frames all resolve and are documented")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
