#!/usr/bin/env python3
"""Generate the client shot guide from the pipeline's own rules.

    python3 docs/shot_guide.py

Writes three files into docs/:
    shot-guide-agent.md         plain language, for listing agents
    shot-guide-photographer.md  technical, for photographer partners
    shot-guide-checklist.md     printable one-pager for on site

WHY THIS IS GENERATED AND NOT WRITTEN

The rules already live in code: REQUIRED_ANCHORS, the photo-count floor in
_audit, the room taxonomy in rooms.py, the viewpoint rules in viewpoint.py. A
hand-written guide drifts from the validator the first time either changes, and
the drift surfaces as a client who followed the instructions and still got
warnings. One source of truth, or it breaks.

Change a constant, re-run this, and every version updates together.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "pipeline"))

from flythrough.planner import REQUIRED_ANCHORS          # noqa: E402
from flythrough.rooms import NON_HERO, TOUR_ORDER, resolve  # noqa: E402

OUT = ROOT / "docs"

# Plain-English names for the canonical rooms, used in the agent version.
PLAIN: dict[str, str] = {
    "street": "The street / driveway approach",
    "exterior": "The front of the house",
    "entry": "The entry or front hallway",
    "living": "The main living room",
    "kitchen": "The kitchen",
    "dining": "The dining area",
    "office": "The office or study",
    "hallway": "A connecting hallway or stairs",
    "primary_bed": "The primary bedroom",
    "primary_bath": "The primary bathroom",
    "bedroom": "Any other bedroom",
    "bathroom": "Any other bathroom",
    "laundry": "The laundry / utility room",
    "basement": "The lower level",
    "garage": "The garage",
    "patio": "The patio, deck or porch",
    "pool": "The pool",
    "yard": "The yard or grounds",
    "view": "The view (water, mountains, skyline)",
    "aerial": "An aerial / drone shot, if you have one",
}

# What the camera should be doing, per room. Written for someone holding a phone.
HOW_AGENT: dict[str, str] = {
    "street": "Stand at the end of the driveway, facing the house. Get the whole property in frame.",
    "exterior": "Stand on the walkway square to the front of the house. Keep the camera level -- do not tilt up.",
    "entry": "Stand just inside the front door, looking in the direction a visitor would walk.",
    "living": "Stand in the doorway you enter by, with the far side of the room in frame.",
    "kitchen": "Stand where you can see the island or main counter and the way through to the next room.",
    "dining": "Frame the table with the doorway you came from behind you.",
    "primary_bed": "Stand in the doorway. Get the bed and the window in one frame.",
    "primary_bath": "Stand in the doorway. Keep the mirror out of your own reflection.",
    "patio": "Stand on the lawn looking back at the house, so the doors you came out of are visible.",
    "pool": "Include the house in the background, not just the water.",
    "yard": "Shoot back toward the house so the yard reads as belonging to it.",
    "view": "Shoot from where a buyer would actually stand to look at it.",
    "aerial": "IMPORTANT -- see the aerial rule below.",
}

PHOTO_MIN, PHOTO_IDEAL_LO, PHOTO_IDEAL_HI = 4, 8, 14


def _anchor_lines(plain: bool) -> str:
    src = PLAIN if plain else {k: k.replace("_", " ") for k in PLAIN}
    return "\n".join(
        f"{i}. **{src[a]}**" + (f" — {HOW_AGENT[a]}" if plain and a in HOW_AGENT else "")
        for i, a in enumerate(REQUIRED_ANCHORS, 1)
    )


def _tour_table() -> str:
    rows = []
    for key in TOUR_ORDER:
        req = "**required**" if key in REQUIRED_ANCHORS else ""
        hero = "" if key not in NON_HERO else "never used as the cover frame"
        rows.append(f"| {PLAIN.get(key, key)} | `{key}` | {req} | {hero} |")
    return "\n".join(rows)


HEADER = """<!-- GENERATED by docs/shot_guide.py -- do not edit by hand.
     Rules come from planner.REQUIRED_ANCHORS, rooms.TOUR_ORDER and
     viewpoint.assess. Change those, then re-run the generator. -->
"""

AERIAL_RULE_SHORT = (
    "If you send an aerial, it must be shot over **the same side of the house** "
    "as the outdoor photo before it, and the filename must say which side "
    "(`rear-aerial.jpg`)."
)


def agent_guide() -> str:
    return f"""{HEADER}
# What photos to send — a 60-second guide

You do not need to shoot anything new. **Send the photos you already have.**
This tells you which ones, and what to add if something is missing.

## The short version

- **{PHOTO_MIN} photos minimum. {PHOTO_IDEAL_LO}–{PHOTO_IDEAL_HI} is the sweet spot.**
- **Landscape, not portrait.** Turn the phone sideways.
- **Originals, straight off the camera or phone.** Do not crop, filter or brighten
  them. We do not edit your photos either — that is deliberate, and it is what
  keeps the finished video compliant.
- **Name each file after the room**: `kitchen.jpg`, `master-bedroom.jpg`. If you
  number them (`01_`, `02_`) we will keep that exact order.

## The three we cannot make a tour without

{_anchor_lines(plain=True)}

Without these the video still renders, but it reads as incomplete to a buyer, and
we will tell you so before we charge you for it.

## Then add as many of these as you have

Order does not matter — we sequence them the way a buyer walks the house.

| Room | Name the file | | |
|---|---|---|---|
{_tour_table()}

## Two rules that matter more than they look

**1. The aerial rule.** {AERIAL_RULE_SHORT}

Here is why. The video moves the camera between your photos. If the last ground
photo looks at the **back** of the house and the aerial is framed over the
**front**, there is no path a real drone could fly between them — so the video
has to cross the building, and it comes out looking like a *different house*. We
learned this the hard way on our own test.

**2. Do not jump from the front of the house to the back with nothing in between.**
Send a side view, or an aerial, as the bridge.

## What makes a photo unusable

- Portrait orientation
- Heavily filtered, HDR-crunched or brightened
- A room shot so tight there is no doorway or opening visible
- People or pets in frame
- Screenshots of photos, or photos re-saved from a text message

## What happens next

Send the folder. We check it, tell you within a couple of hours if anything is
missing, and deliver the video the next day.
"""


def photographer_guide() -> str:
    return f"""{HEADER}
# Capture specification — photographer partners

You already shoot these properties. This is what makes a set convert cleanly into
a flythrough, and the two capture rules that cannot be fixed downstream.

## Deliverable

- **{PHOTO_MIN} frames minimum, {PHOTO_IDEAL_LO}–{PHOTO_IDEAL_HI} typical.** Landscape, 16:9-croppable.
- Full-resolution originals. No retouching, no sky replacement, no virtual
  staging. **We do not alter supplied stills** — the client's disclosure page has
  to contain genuine originals, so any edit breaks the compliance position for
  both of us.
- Filename carries the room: `04_great-room.jpg`. A `rooms.json` sidecar mapping
  filename → room overrides the filename and always wins.

## Required coverage

{_anchor_lines(plain=False)}

## The two capture rules

### 1. Match exposure and white balance between ADJACENT frames

This is the one that separates a professional set from an amateur one here.

The video generates the travel between two of your frames. Where those two frames
disagree on white balance or exposure, the transition **pops** at the seam. It
cannot be fully corrected afterwards, and correcting it in the render is
forbidden by our own never-patch-output rule.

- Lock white balance across the interior set. Do not let auto WB drift between a
  north-facing bedroom and a west-facing kitchen.
- Keep interiors within roughly a stop of each other.
- Shoot the whole property in one lighting session where you can. A kitchen shot
  at 9am and a living room at 5pm will seam badly even though both are excellent
  photographs.

### 2. The aerial must be framed over the same elevation as the ground frame preceding it

{AERIAL_RULE_SHORT}

There is no continuous camera path between a ground view of one elevation and an
overhead view of the opposite one. Asked to make one, the model crosses the
building and reconstructs the far side — the output reads as a second property.

Practical rule: **shoot the aerial from over whichever side your last ground
exterior was taken from**, and name it `rear-aerial.jpg` or `front-aerial.jpg`.
Our planner reads that name and validates it.

Corollary: never hand over a front elevation and a rear elevation with nothing
between them. Include a side elevation or an aerial as the bridge.

## Technical

| | |
|---|---|
| Lens | 16–24mm equivalent. Wider distorts; longer breaks the sense of travel. |
| Verticals | Straight. Correct in-camera or with a tilt-shift, not by warping later. |
| Height | Chest height, ~1.4m, consistent across interiors. |
| Framing | Include the doorway or opening that leads onward — that is what the camera travels through. |
| People | None. Not in frame, not in mirrors, not in windows. |

## Rooms that are never used as a cover frame

{", ".join(sorted(NON_HERO))} — shoot them if they matter to the listing, but they
will never be chosen as the thumbnail.

## Partner economics

You sell at $349. You pay $199. No new equipment, no pilot certificate, no second
site visit. Next-day turnaround. Every delivery ships with the AI disclosure
already generated — burned into the video, plus a hosted page carrying the
unaltered originals, which is what California's AB 723 actually requires.
"""


def checklist() -> str:
    req = "\n".join(f"- [ ] {PLAIN[a]}" for a in REQUIRED_ANCHORS)
    opt = "\n".join(
        f"- [ ] {PLAIN[k]}" for k in TOUR_ORDER if k not in REQUIRED_ANCHORS
    )
    return f"""{HEADER}
# Shot checklist — print this

**{PHOTO_MIN} minimum · {PHOTO_IDEAL_LO}–{PHOTO_IDEAL_HI} ideal · landscape · originals only · name files by room**

## Must have
{req}

## Add what exists
{opt}

## Before you send
- [ ] Every file is landscape
- [ ] Nothing has been filtered, cropped or brightened
- [ ] No people, pets or reflections of you
- [ ] Interiors shot in one lighting session, white balance locked
- [ ] Aerial (if any) is over the SAME side as the last ground exterior
- [ ] Aerial filename says which side: `rear-aerial.jpg`
- [ ] Front and rear elevations are not adjacent with nothing between them
"""


def main() -> int:
    files = {
        "shot-guide-agent.md": agent_guide(),
        "shot-guide-photographer.md": photographer_guide(),
        "shot-guide-checklist.md": checklist(),
    }
    for name, body in files.items():
        (OUT / name).write_text(body)
        print(f"  wrote {name}  ({len(body.splitlines())} lines)")

    # Acceptance criterion: every room named in the guide must resolve.
    bad = [k for k in PLAIN if resolve(k).key != k]
    if bad:
        print(f"  FAIL: names that do not resolve: {bad}")
        return 1
    print(f"  all {len(PLAIN)} room names resolve through rooms.resolve()")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
